name: Build Docker Container and push to ECR
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        name: Build And Deploy to AWS
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE }}
                  role-session-name: ghsession
                  aws-region: ${{ secrets.AWS_REGION }}
                  
            - name: Log in to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build, tag, and push docker image to Amazon ECR
              id: build-and-push
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  ECR_REPOSITORY: project-flight
                  IMAGE_TAG: ${{ github.sha }}
              run: |
                  docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
